### ISSUE TITLE
面包数据不分群,方便备份以及可观

### ISSUE THREAD

**Issue by Jerry080801** [Mai-icy/nonebot-plugin-bread-shop#12]
建议开关面包数据不分群,方便备份以及可观
建议配置文件

**Comment by Mai-icy** [comment]
那随机抢和随机赠送操作的随机对象将只能事群内用户

**Comment by Mai-icy** [comment]
将在几天后添加

**Comment by Mai-icy** [comment]
已在https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/3c16151ea3510bb69163133ad57816ae4d0a2d56 中添加，若有操作问题，请提出
