### ISSUE TITLE
无法从nonebot.adapters.onebot.exception中引入ActionFailed

### ISSUE THREAD

**Issue by lyha23** [Mai-icy/nonebot-plugin-bread-shop#13]
提示如下
![F5F62372249CB7444AC28189A5AB2A87](https://user-images.githubusercontent.com/75962592/184793720-36cab7dd-95e6-4c62-b1a3-c8af55498112.png)

经过群里大佬提示，改为以下即可
![截屏2022-08-16 11 47 16](https://user-images.githubusercontent.com/75962592/184793834-8c8fab25-b5e0-40e2-9eba-34ce2d5b1b5e.png)

**Comment by Mai-icy** [comment]
好像是版本问题，经测试`from nonebot.exception import ActionFailed`也可以捕获

**Comment by Mai-icy** [comment]
已经修改 https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/cc343b4f721c9f7974211d9ac25b4bb355327ee1
