### ISSUE TITLE
恢复触发at效果

### ISSUE THREAD

**Issue by LoCCai** [Mai-icy/nonebot-plugin-bread-shop#14]
建议通过此方式构建
msg_at = MessageSegment.at(user_id = user_qq)

**Comment by Mai-icy** [comment]
因为看别人说at多了会引发风控，所以把at消息改成纯文本了

**Comment by Mai-icy** [comment]
在https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/995f010d113a259ab0419d5d3d0ee677c2be2d7e 中去掉的

在源代码体现为
```    
# msg_at = Message(f"[CQ:at,qq={user_qq}]")
msg_at = Message("@" + name)
```
可以自行去掉注释和注释下一句

**Comment by Mai-icy** [comment]
在https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/4eec1d13263273e0c71933bd90142f0215673ead 中添加
可在配置文件中选择
