### ISSUE TITLE
建议添加一个等级排行

### ISSUE THREAD

**Issue by Goodzzzz** [Mai-icy/nonebot-plugin-bread-shop#16]

**Comment by Mai-icy** [comment]
面包排行优先以等级作为标准，README中已指出触发指令为`breadtop`或者`面包排名`
指令示例：`/breadtop 11 20`
为查看第11名到第20名，不指出范围默认为前5名

**Comment by Mai-icy** [comment]
不好意思README写错了
change at https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/f6144dfe29316c5b7482eb9966fbcad9e2eca84b

**Comment by Mai-icy** [comment]
请问是否解决您的问题，若还有其他问题请`Reopen`此issue
