### ISSUE TITLE
排行功能在全局模式无法使用

### ISSUE THREAD

**Issue by Tloml-Starry** [Mai-icy/nonebot-plugin-bread-shop#17]
请问排行功能在全局模式是无法使用吗，会有以下报错
[message]Running Matcher(type='message', module=nonebot_plugin_bread_shop) failed.
另外，如果可以，能否将排行以图片方式显示

**Comment by Mai-icy** [comment]
是否有更详细的报错信息，我最近不怎么方便测试代码

**Comment by Tloml-Starry** [comment]
好的，这是全部
![QQ截图20230215161100](https://user-images.githubusercontent.com/109225278/218969854-f1e50596-d4c1-49c5-a634-3cf005e995df.png)

**Comment by Mai-icy** [comment]
fix at https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/92f6390f7b789f85290fce2c793f384cc906259a
请尝试一下是否修复（我没有测试环境）

**Comment by Mai-icy** [comment]
关于排行榜图片功能，我最近在准备高考，暂时没有时间处理。
如果您有python的一定基础，可尝试修改`__init__.py`文件内的`get_group_top()`函数
```python
async def get_group_top(bot: Bot, group_id, thing, start=1, end=5) -> Message:
    """获取群内（或全局）排行榜"""
    if group_id == "global":
        group_member_list = []
    else:
        group_member_list = await bot.get_group_member_list(group_id=int(group_id))

    user_id_list = {info['user_id'] for info in group_member_list}
    all_data = BreadDataManage(group_id).get_all_data()
    num = 0
    append_text = f"🍞本群{thing}排行top！🍞\n"
    for data in all_data:
        if int(data.user_id) in user_id_list or group_id == "global":
            num += 1
            if start <= num <= end:
                name = await get_nickname(bot, data.user_id, group_id)
                append_text += f"top{num} : {name} Lv.{data.bread_eaten // LEVEL}，拥有{thing}{data.bread_num}个\n"
            if num > end:
                break

    append_text += "大家继续加油w！"
    return Message(append_text)
```
其中代码稍微有些乱，但应该不难理解，您只需要导入`PIL`创建您的画布绘制出图片
创建图片对应的 `MessageSegment` 类型，读取内存中的图片数据，并且代替原来的 `return Message(append_text)` 返回您的图片
`MessageSegment`即可，我在之后会考虑添加的

**Comment by Tloml-Starry** [comment]
好的，非常感谢您在百忙之中回复我，祝您学业顺利！

**Comment by Mai-icy** [comment]
如果更新了代码没有报错了可以close了，我不敢保证完全正确

**Comment by Mai-icy** [comment]
将在明天更新至pypi

**Comment by Tloml-Starry** [comment]
好的，谢谢，我待会会进行测试

**Comment by Tloml-Starry** [comment]
谢谢，经过测试，排行功能已经能正常使用了

**Comment by Mai-icy** [comment]
感谢您对本插件的关注，我将关闭此issue
