### ISSUE TITLE
使用的时候出现报错

### ISSUE THREAD

**Issue by shmilyty** [Mai-icy/nonebot-plugin-bread-shop#2]
![image](https://user-images.githubusercontent.com/61276699/176192942-4955bee7-8664-4573-94d3-90a74119290c.png)
![image](https://user-images.githubusercontent.com/61276699/176193104-93f56d6b-ab4f-4ef6-a457-3a001a237b86.png)
调用`>买面包`时报错，不运行
在加载插件时也有类似的报错
![image](https://user-images.githubusercontent.com/61276699/176193453-38bab97f-1f49-465f-aca1-285f95baf725.png)
是我哪里没有正确配置吗（没有修改过代码文件）

**Comment by Lu-Qi-777** [comment]
在bot的/data目录下`mkdir bread`然后重启一下bot.py逝世？

**Comment by shmilyty** [comment]
解决了，谢谢

**Comment by Mai-icy** [comment]
已进行对应修复（创建文件夹的时候没有考虑父级目录是否存在）
fix at https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/dd17b05e89f0cfc2c8aeee9e4556edc12934c143
