### ISSUE TITLE
对插件的使用建议

### ISSUE THREAD

**Issue by linword** [Mai-icy/nonebot-plugin-bread-shop#3]
送面包能设置成指定数量嘛？如果没有数量就随机，另，希望可以在.env.*里改更改配置项，大佬辛苦了，插件很有意思！

**Comment by Mai-icy** [comment]
前面那一点已在https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/8ec53630bead98f1c6d29479b6dcaa66b6566f83中实现，并且可以设置全部的事件是否随机（可分群）
由于对框架还不熟悉，“在.env.*里改更改配置项” 将在晚些时候添加

**Comment by linword** [comment]
好的，谢谢

**Comment by Mai-icy** [comment]
https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/06cd3f816d89d9c14148dea6872c22011c03c12c
已经移至env

**Comment by linword** [comment]
请问大佬我是在 .env.prod 是如下配置的：
```
cd_buy = 1800
cd_eat = 3600
cd_rob = 1800
cd_give = 1800
cd_bet = 3600
level_bread_num=20
special_thing_group:{"666488548":["炸鸡", "面包"]}
```
但是运行之后，配置并未生效，请问是哪里配置错了？

**Comment by Mai-icy** [comment]
请将`special_thing_group:{"xxxxxx":["炸鸡", "面包"]}`修改为`special_thing_group={"xxxxxx":["炸鸡", "面包"]}`后尝试

**Comment by linword** [comment]
我改了也未生效，只能从config里改嘛？我把配置放在.env里也未生效

**Comment by Mai-icy** [comment]
我这里测试放在`.env.prod`配置中是生效的，请检查`.env`内容是否为`ENVIRONMENT=prod`

**Comment by linword** [comment]
对的，我的环境设置是没错的，确实是`ENVIRONMENT=prod`，但就是不生效，太奇怪了，和python版本及nonebot2版本应该是没关系的吧？

**Comment by Mai-icy** [comment]
有无出现`Python-dotenv could not parse statement starting at line x`类似字样

**Comment by linword** [comment]
嗯嗯
`Python-dotenv could not parse statement starting at line 50`

**Comment by linword** [comment]
已找到原因了，第五十行的错误是由于之前的`special_thing_group:{"xxxxxx":["炸鸡", "面包"]}`的冒号原因。
我用的`pip install nonebot-plugin-bread-shop`这个命令并不会升级，对比了线上的代码，发现本地的代码和线上的不一致，应该是`pip  install nonebot-plugin-bread-shop -U`或者`pip  install nonebot-plugin-bread-shop --upgrade`。
大佬辛苦了，谢谢。
