### ISSUE TITLE
买不了面包

### ISSUE THREAD

**Issue by ATTomatoo** [Mai-icy/nonebot-plugin-bread-shop#4]
![35G1RO1 KB4I6X~BPMKC38B](https://user-images.githubusercontent.com/93612024/176990028-9cda202f-efce-41dd-ab88-6d013fae5f20.png)
c
![ND3AT49LMXH _@MGHY6EQRV](https://user-images.githubusercontent.com/93612024/176990030-ae8c2e73-4ae8-4702-a64a-1ad29344b086.png)
插件有正常加载，但是不能正常买面包

**Comment by Mai-icy** [comment]
fix at https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/ff04b5d44e26695c567a3d422865b5410808c453
感谢提出
将在v0.1.6修复

**Comment by Mai-icy** [comment]
已发布v0.1.6 https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/8eb41bd2670c6dab37b877a0ca3fece46b12c277
