### ISSUE TITLE
特别处理群设置

### ISSUE THREAD

**Issue by Danwk2333** [Mai-icy/nonebot-plugin-bread-shop#6]
请问可以在【special_操作名_group：设置特别处理的群】添加更改名字吗，针对不同的群使用不用的美食，a群默认买面包，b群单独设置买鸡腿

**Comment by Mai-icy** [comment]
此功能已添加 https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/c5a96d365c95368d5eee99838fcda67be4052c2f
见配置项 special_thing_group
