### ISSUE TITLE
请问我要想给thing设置多个词该怎么办呢

### ISSUE THREAD

**Issue by qjksxy** [Mai-icy/nonebot-plugin-bread-shop#7]
比如想给设置为发送吃面包或者吃水果都生效。

**Comment by Mai-icy** [comment]
请问是面包和水果同一数据库（也就是两者代表同一物）还是两者需要不同数据库，作为两个不同事物管理。

**Comment by Mai-icy** [comment]
将在几天后添加，这几天休息

**Comment by Mai-icy** [comment]
> 比如想给设置为发送吃面包或者吃水果都生效。

请更详细地描述需求

**Comment by qjksxy** [comment]
是这样的，例如如下场景：
我想在某一天或活动期间临时的更改面包为草莓。但是会有群友并不知晓这一变化，所以我预期是此时群友输入吃面包或者吃草莓都能触发相应操作，同时机器人返回结果为草莓以提示用户这一临时变化。当活动结束后，恢复为面包。



在 2022-07-10 16:13:54，"maiicy" ***@***.***> 写道：

比如想给设置为发送吃面包或者吃水果都生效。

请更详细地描述需求

**Comment by Mai-icy** [comment]
已添加该功能https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/d8a2ec8a6318c1bd19c29feeaaaad52498320b8a
将`special_thing_group`配置为 `{"群号": ["草莓", "面包"]}` 即可

**Comment by qjksxy** [comment]
收到！
