### ISSUE TITLE
面包记录存在问题

### ISSUE THREAD

**Issue by qjksxy** [Mai-icy/nonebot-plugin-bread-shop#8]
面包记录查询时，猜拳次数总是与吃次数相同，而非正确的数值。
经检查，__init__.py  line310 和 316中存在拼写错误，猜拳字段错误拼写为user_log.eat_times。望修正

**Comment by Mai-icy** [comment]
感谢提出
fix at https://github.com/Mai-icy/nonebot-plugin-bread-shop/commit/2e37cf5cec85a21e27f8acb2fa87b872b04de1b8
