### ISSUE TITLE
能不能限定一周中的哪几天来自动开启面包店，其他时间为关闭

### ISSUE THREAD

**Issue by xiaoxianyu233** [Mai-icy/nonebot-plugin-bread-shop#9]

**Comment by Mai-icy** [comment]
请先更新到最新版本v0.1.11

**Comment by Mai-icy** [comment]
在`bread_event.py`文件中进行修改
先导入获取时间的模块
`from datetime import datetime`
再在文件下面添加该示例函数
```python
# 全事件
@probability(1, Action.ALL, priority=1, group_id_list=["群号"])
def closing_time(event: _Event):
    if datetime.now().weekday() in (0, 1, 2, 3):
        event.bread_db.reduce_user_log(event.user_id, event.event_type)
        return f"{event.thing}店已打烊！"
```
其中`group_id_list`可以不设置，将为全部群聊
`(0, 1, 2, 3)`代表周一周二周三周四
`return f"{event.thing}店已打烊！"`是bot回复内容

以上事件内容为 在指定群号内，优先级为1，所有操作，概率为100%。周一周二周三周四均打烊

**Comment by linword** [comment]
大佬，按照这个思路，我想只在周四把 面包 全局换成 炸鸡，`if datetime.now().weekday() in (3):`后面应该咋写

**Comment by Mai-icy** [comment]
先导入配置文件的变量，在上面改为
`from .config import MIN, MAX, LEVEL, bread_config`
在这个语句后面使用`bread_config.bread_thing = ["炸鸡", "面包"]`即可
并且去掉`return`语句
但是问题在于，周四第一个操作的人还是面包，在有一个人操作了之后才会变化

**Comment by Mai-icy** [comment]
`event.bread_db.reduce_user_log(event.user_id, event.event_type)`这句只是不计算用户访问次数

上面这个问题的另一个解决方法就是可以通过修改return内容提示用户已经进入星期四，并且让用户再输入一次即可（第一个用户需要使用面包来触发）

这个方法需要设置一个全局变量

**Comment by Mai-icy** [comment]
> 大佬，按照这个思路，我想只在周四把 面包 全局换成 炸鸡，`if datetime.now().weekday() in (3):`后面应该咋写

明天给你一个例子

**Comment by xiaoxianyu233** [comment]
> 在`bread_event.py`文件中进行修改 先导入获取时间的模块 `from datetime import datetime` 再在文件下面添加该示例函数
> 
> ```python
> # 全事件
> @probability(1, Action.ALL, priority=1, group_id_list=["群号"])
> def closing_time(event: _Event):
>     if datetime.now().weekday() in (0, 1, 2, 3):
>         event.bread_db.reduce_user_log(event.user_id, event.event_type)
>         return f"{event.thing}店已打烊！"
> ```
> 
> 其中`group_id_list`可以不设置，将为全部群聊 `(0, 1, 2, 3)`代表周一周二周三周四 `return f"{event.thing}店已打烊！"`是bot回复内容
> 
> 以上事件内容为 在指定群号内，优先级为1，所有操作，概率为100%。周一周二周三周四均打烊

感谢大佬

**Comment by Mai-icy** [comment]
> 大佬，按照这个思路，我想只在周四把 面包 全局换成 炸鸡，`if datetime.now().weekday() in (3):`后面应该咋写

建议重新开一个issue
